version: '3.1'
services :
  java:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - app
  postgres:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    networks:
      - app
networks:
  app:
    driver: bridge